apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fstop-rd-nctu-me-tls
spec:
  secretName: fstop-rd-nctu-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fstop-rd.nctu.me
  dnsNames:
    - fstop-rd.nctu.me
    - www.fstop-rd.nctu.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fstop-rd.nctu.me
          - www.fstop-rd.nctu.me
