apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kfclts-nctu-me-tls
spec:
  secretName: kfclts-nctu-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kfclts.nctu.me
  dnsNames:
    - kfclts.nctu.me
    - www.kfclts.nctu.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kfclts.nctu.me
          - www.kfclts.nctu.me
